export const modalTypes = {
   DASHBOARD_TITLE: "DASHBOARD_TITLE",
   CREATE_NEW_PATIENT_MODAL: "CREATE_NEW_PATIENT_MODAL",
   OPEN_MESSAGE: "OPEN_MESSAGE",
   OPEN_NOTIFICATION: "OPEN_NOTIFICATION",
   OPEN_PROFILE_OPTIONS: "OPEN_PROFILE_OPTIONS",
   OPEN_PATIENT_OPTIONS: "OPEN_PATIENT_OPTIONS",
   OPEN_PATIENT_VITAL_EDIT_MODAL: "OPEN_PATIENT_VITAL_EDIT_MODAL",
   SELECTED_PATIENT_OPTION_ID: "SELECTED_PATIENT_OPTION_ID",
   SET_ACTIVITY_ID: "SET_ACTIVITY_ID",
   OPEN_GOALS_FORM: "OPEN_GOALS_FORM",
};
