export const PATIENT_BASICS = [
   {
      id: 1,
      label: "Patient ID *",
      type: "text",
      name: "patientID",
      required: "required",
      placeholder: "Patient ID",
   },
   {
      id: 2,
      label: "First name *",
      type: "text",
      name: "firstName",
      required: "required",
      placeholder: "First name",
   },
   {
      id: 3,
      label: "Last name *",
      type: "text",
      name: "lastName",
      required: "required",
      placeholder: "Last name",
   },
   {
      id: 4,
      label: "DOB *",
      type: "date",
      name: "dob",
      required: "required",
      placeholder: "Date of birth",
   },
   {
      id: 5,
      label: "Gender *",
      type: "select",
      name: "gender",
      required: "required",
      placeholder: "Gender",
      options: [
         { id: 1, optionOne: "Male" },
         { id: 2, optionOne: "Female" },
      ],
   },
   {
      id: 6,
      label: "Phone number",
      type: "text",
      name: "preferredCommunication",
      placeholder: "+4915217473772",
   },
   {
      id: 7,
      label: "Languages",
      type: "text",
      name: "language",
      required: "required",
      placeholder: "List of languages",
      info: 'Seperate each item with a comma ","',
   },
];

export const PATIENT_MEDICALS = [
   {
      id: 8,
      label: "Admitted Date",
      type: "date",
      name: "admittedDate",
      placeholder: "Admitted on",
   },
   {
      id: 9,
      label: "Last appointment",
      type: "date",
      name: "lastAppointment",
      placeholder: "Last appointment",
   },
   {
      id: 10,
      label: "Conditions",
      type: "text",
      name: "conditions",
      placeholder: "List of conditions",
      info: '* Seperate each item with a comma ","',
   },
   {
      id: 11,
      label: "Diagnosis",
      type: "text",
      name: "diagnosis",
      placeholder: "List of Diagnosis",
      info: '* Seperate each item with a comma ","',
   },
   {
      id: 12,
      label: "Medications",
      type: "text",
      name: "medications",
      placeholder: "List of medications",
      info: '* Seperate each item with a comma ","',
   },
   {
      id: 13,
      label: "Allergies",
      type: "text",
      name: "allergies",
      placeholder: "List of allergies",
      info: '* Seperate each item with a comma ","',
   },

   {
      id: 14,
      label: "Treatment status",
      type: "number",
      name: "status",
      placeholder: "Treatment status",
   },
   {
      id: 15,
      label: "Recovery",
      type: "number",
      name: "recovery",
      placeholder: "Recovery",
   },
   {
      id: 16,
      label: "Test",
      type: "number",
      name: "test",
      placeholder: "Test",
   },
];
