export const NEWGOALS = [
   {
      id: 1,
      type: "text",
      name: "activityId",
      placeholder: "Activity ID",
      label: "Activity ID *",
      required: true,
      disabled: true,
   },
   {
      id: 2,
      type: "text",
      name: "subject",
      placeholder: "Subject",
      label: "Subject *",
      required: true,
   },
   {
      id: 3,
      type: "select",
      name: "priority",
      placeholder: "Priority",
      label: "Priority *",
      required: true,
      options: [
         { id: 1, optionOne: "High" },
         { id: 2, optionOne: "Medium" },
         { id: 3, optionOne: "Low" },
      ],
   },
   {
      id: 4,
      type: "date",
      name: "date",
      placeholder: "Date",
      label: "Date *",
      required: true,
   },
   {
      id: 5,
      type: "number",
      name: "status",
      placeholder: "Status",
      label: "Status",
   },
   {
      id: 6,
      type: "select",
      name: "frequency",
      placeholder: "Frequency",
      label: "Frequency *",
      required: true,
      options: [
         { id: 1, optionOne: "Daily" },
         { id: 2, optionOne: "Weekly" },
         { id: 3, optionOne: "Monthly" },
      ],
   },
];
