export const formTypes = {
   INCREASE_CURRENT_STEP: "INCREASE_CURRENT_STEP",
   DECREASE_CURRENT_STEP: "DECREASE_CURRENT_STEP",
   RESET_FORM_STEP: "RESET_FORM_STEP",
   SET_PATIENTID: "SET_PATIENTID",
};
