export const dashboardTypes = {
   DASHBOARD_TITLE: "DASHBOARD_TITLE",
   CREATE_NEW_PATIENT_MODAL: "CREATE_NEW_PATIENT_MODAL",
   OPEN_MESSAGE: "OPEN_MESSAGE",
   OPEN_NOTIFICATION: "OPEN_NOTIFICATION",
   OPEN_PROFILE_OPTIONS: "OPEN_PROFILE_OPTIONS",
};
