export const PATIENT_BASICS = [
   {
      id: 1,
      label: "Patient ID*",
      type: "text",
      name: "patientID",
      required: "required",
      placeholdertext: "Patient ID",
   },
   {
      id: 2,
      label: "First name*",
      type: "text",
      name: "firstName",
      required: "required",
      placeholdertext: "First name",
   },
   {
      id: 3,
      label: "Last name*",
      type: "text",
      name: "lastName",
      required: "required",
      placeholdertext: "Last name",
   },
   {
      id: 4,
      label: "DOB*",
      type: "date",
      name: "dob",
      required: "required",
      placeholdertext: "Date of birth",
   },
   {
      id: 5,
      label: "Gender*",
      type: "text",
      name: "gender",
      required: "required",
      placeholdertext: "Gender",
   },
   {
      id: 6,
      label: "Phone number",
      type: "text",
      name: "preferredCommunication",
      placeholdertext: "+4915217473772",
   },
   {
      id: 7,
      label: "Languages",
      type: "text",
      name: "language",
      required: "required",
      placeholdertext: "List of languages",
      info: 'Seperate each item with a comma ","',
   },
];

export const PATIENT_MEDICALS = [
   {
      id: 8,
      label: "Admitted on",
      type: "date",
      name: "admittedDate",
      placeholdertext: "Admitted on",
   },
   {
      id: 9,
      label: "Conditions",
      type: "text",
      name: "conditions",
      placeholdertext: "List of conditions",
      info: 'Seperate each item with a comma ","',
   },
   {
      id: 10,
      label: "Diagnosis",
      type: "text",
      name: "diagnosis",
      placeholdertext: "List of Diagnosis",
      info: 'Seperate each item with a comma ","',
   },
   {
      id: 11,
      label: "Medication",
      type: "text",
      name: "medications",
      placeholdertext: "List of medication",
      info: 'Seperate each item with a comma ","',
   },
   {
      id: 12,
      label: "Allergies",
      type: "text",
      name: "allergies",
      placeholdertext: "List of allergies",
      info: 'Seperate each item with a comma ","',
   },
   {
      id: 13,
      label: "Last appointment",
      type: "date",
      name: "lastAppointment",
      placeholdertext: "Last appointment",
   },
   {
      id: 14,
      label: "Treatment status",
      type: "number",
      name: "status",
      placeholdertext: "Treatment status",
   },
   {
      id: 15,
      label: "Recovery",
      type: "number",
      name: "recovery",
      placeholdertext: "Recovery",
   },
   {
      id: 16,
      label: "Test",
      type: "number",
      name: "test",
      placeholdertext: "Test",
   },
];
