export const CardsData = [
   {
      id: 1,
      total: 270,
      subtitle: "Total Patient",
      backgroundcolor: "#1665FF",
      textcolor: "#797979",
      width: "100%",
      icon: "/icons/sick-white.svg",
      changeInfo: "10% higher than last month",
      changeDirection: 1,
      link: "Patients",
   },
   {
      id: 2,
      total: 84,
      subtitle: "Discharged Patients",
      backgroundcolor: "#00E2BB",
      textcolor: "#797979",
      width: "100%",
      icon: "/icons/discharge-white.svg",
      changeInfo: "25% lower than last month",
      changeDirection: 0,
      link: "Patients",
   },
   {
      id: 3,
      total: 75,
      subtitle: "Admitted Patients",
      backgroundcolor: "#00D0E9",
      textcolor: "#797979",
      width: "100%",
      icon: "/icons/admitted-white.svg",
      changeInfo: "15% higher than last month",
      changeDirection: 1,
      link: "Patients",
   },
   {
      id: 4,
      total: 14,
      subtitle: "Upcoming Appointments",
      backgroundcolor: "#306ef6",
      textcolor: "#797979",
      width: "100%",
      icon: "/icons/appointment-white.svg",
      changeInfo: "5% higher than last month",
      changeDirection: 1,
      link: "Appointments",
   },
];
