export const CardsData = [
   {
      id: 1,
      total: 270,
      subtitle: "Total Patient",
      backgroundcolor: "#396CFF",
      textcolor: "#797979",
      width: "100%",
      icon: "/icons/sick-white.svg",
   },
   {
      id: 2,
      total: 84,
      subtitle: "Discharged Patients",
      backgroundcolor: "#57C2FF",
      textcolor: "#797979",
      width: "100%",
      icon: "/icons/discharge-white.svg",
   },
   {
      id: 3,
      total: 75,
      subtitle: "Admitted Patients",
      backgroundcolor: "#55EDFF",
      textcolor: "#797979",
      width: "100%",
      icon: "/icons/admitted-white.svg",
   },
   {
      id: 4,
      total: 14,
      subtitle: "Upcoming Appointments",
      backgroundcolor: "#9597EC",
      textcolor: "#797979",
      width: "100%",
      icon: "/icons/appointment-white.svg",
   },
];
