export const SingleUserDetails = {
   userAvatar: "/images/Arlene.png",
   Name: "Alma Lawson",
   Dob: "June 2, 1994 (27 years)",
   Gender: "Female",
   Man: "SD9212969",
   Address: "2464 Royal Ln. Mesa, New Jersey 45463",
   PreferredCommunication: "+49 15712345 989",
   Language: ["English", "German", "Yoruba"],
   Insurance: { "Member ID": "S763264973", provider: "DAK Insurance" },
   Conditions: [
      "Essential hypertension",
      "Moderate chronic obstructive pulmonary disease",
      "Type 2 diabetes uncontrolled",
   ],
   Medications: [
      "Avandia",
      "BO Ultratine Needles",
      "Insulin",
      "Usinipirol",
      "Medormin",
      "Prandin",
      "Nabeglindide",
      "Strivendi",
      "Respimat",
   ],
   Allergies: ["Oenicillin", "Sutta"],
   LastAppointment: "8 Sep, 2022, 05:36 pm",
   Vitals: [
      {
         id: "1",
         icon: "/icons/medical icons.png",
         vitalType: "Blood Pressure",
         vitalNumber: "120/80",
         unit: "",
         color: "#083ACB",
         changeInfo: "25% higher than last month",
         changeDirection: 1,
      },
      {
         id: "2",
         icon: "/icons/medical icons-1.png",
         vitalType: "Heart Rate",
         vitalNumber: "85",
         unit: "bmp",
         color: "#009CF4",
         changeInfo: "10% lower than last month",
         changeDirection: 0,
      },
      {
         id: "3",
         icon: "/icons/medical icons 5.png",
         vitalType: "Glucose",
         vitalNumber: "75 - 90",
         unit: "",
         color: "#00D0E9",
         changeInfo: "15% higher than last month",
         changeDirection: 1,
      },
      {
         id: "4",
         icon: "/icons/medical icons-3.png",
         vitalType: "Cholesterol",
         vitalNumber: "9,456",
         unit: "ml",
         color: "#8C8DB9",
         changeInfo: "5% higher than last month",
         changeDirection: 1,
      },
   ],
};
