export const tableData = [
   {
      id: 1,
      Patient: { Patient: "Esther Howard", Useravatar: "/images/Cameron.png" },
      Age: 25,
      "Admitted Date": "10 Oct, 2021",
      Status: 100,
      Examination: { marker: 1, item: "Ongoing Treatment" },
      Diagnosis: "Influenza",
      Recovery: 90,
      Test: 100,
   },
   {
      id: 2,
      Patient: {
         Patient: "Cameron Williamson",
         Useravatar: "/images/Albert.png",
      },
      Age: 45,
      "Admitted Date": "08 Oct, 2021",
      Status: 20,
      Examination: { marker: 2, item: "Hospitalized" },
      Diagnosis: "Covid-19",
      Recovery: 10,
      Test: 84,
   },
   {
      id: 3,
      Patient: { Patient: "Jenny Wilson", Useravatar: "/images/Floyd.png" },
      Age: 32,
      "Admitted Date": "30 Sept, 2021",
      Status: 34,
      Examination: { marker: 3, item: "On going examination" },
      Diagnosis: "Maleria",
      Recovery: 25,
      Test: 67,
   },
   {
      id: 4,
      Patient: { Patient: "Jacob Jones", Useravatar: "/images/Arlene.png" },
      Age: 39,
      "Admitted Date": "24 Aug, 2021",
      Status: 100,
      Examination: { marker: 1, item: "Ongoing Treatment" },
      Diagnosis: "Diahrreah",
      Recovery: 100,
      Test: 25,
   },
];
