export const tableData = [
   {
      Patient: "Esther Howard",
      Age: 25,
      "Admitted Date": "10 Oct, 2021",
      Status: 100,
      Examination: { marker: 1, item: "Ongoing Treatment" },
      Diagnosis: "Influenza",
      Recovery: 90,
      Test: 100,
   },
   {
      Patient: "Cameron Williamson",
      Age: 45,
      "Admitted Date": "08 Oct, 2021",
      Status: 20,
      Examination: { marker: 2, item: "Hospitalized" },
      Diagnosis: "Covid-19",
      Recovery: 10,
      Test: 84,
   },
   {
      Patient: "Jenny Wilson",
      Age: 32,
      "Admitted Date": "30 Sept, 2021",
      Status: 34,
      Examination: { marker: 3, item: "On going examination" },
      Diagnosis: "Maleria",
      Recovery: 25,
      Test: 67,
   },
   {
      Patient: "Jacob Jones",
      Age: 39,
      "Admitted Date": "24 Aug, 2021",
      Status: 100,
      Examination: { marker: 1, item: "Ongoing Treatment" },
      Diagnosis: "Diahrreah",
      Recovery: 100,
      Test: 25,
   },
];
